name: release

on: [workflow_dispatch]

jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 'lts/*'
            - name: setup semantic-release
              run: npm install -g semantic-release
            - name: checkout
              uses: actions/checkout@v3
            - name: release
              run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}